#ifndef MATRIX_I_MESSAGE_TYPE_H
#define MATRIX_I_MESSAGE_TYPE_H

#include <cstdint>

namespace mmx {

enum : uint32_t {
  IMSG_TYPE_INVALID = 0,

  IMSG_PIPE_NULL_TO_READY,
  IMSG_PIPE_READY_TO_PAUSED,
  IMSG_PIPE_READY_TO_PAUSED_PREROLL,
  IMSG_PIPE_PAUSED_TO_PLAYING,
  IMSG_PIPE_PLAYING_TO_PAUSED,

  IMSG_INPUT_STREAM_IS_READY,

  IMSG_URIDB_SETPROPERTY,

  IMSG_IMAGE_SETPROPERTY,

  IMSG_TYPE_MAXNUM,
};

} // namespace mmx

#endif // MATRIX_I_MESSAGE_TYPE_H