#ifndef MATRIX_I_MESSAGE_TYPE_H
#define MATRIX_I_MESSAGE_TYPE_H

#include <cstdint>

namespace mmx {

enum : uint32_t {
  IMSG_TYPE_INVALID = 0,

  IMSG_PIPE_SET_PLAYING,
  IMSG_PIPE_SET_PLAYING_PENDING,
  IMSG_PIPE_SET_PLAYING_TIMEOUT,
  IMSG_PIPE_SET_PLAYING_SUCCESS,
  IMSG_PIPE_RESET_PLAYING,

  IMSG_INPUT_STREAM_IS_READY,
  IMSG_INPUT_DEVICE_RETRY,

  IMSG_URIDB_SETPROPERTY,

  IMSG_IMAGE_SETPROPERTY,

  IMSG_TYPE_MAXNUM,
};

} // namespace mmx

#endif // MATRIX_I_MESSAGE_TYPE_H